from PySide2 import QtCore, QtGui, QtWidgets
import maya.cmds as cmds

import pokerSpringFunc
reload(pokerSpringFunc)

class PokerUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(281, 133)
        Form.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.buildButton = QtWidgets.QPushButton(Form)
        self.buildButton.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.buildButton.setObjectName("buildButton")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 260, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Line3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.Line3.setContentsMargins(0, 0, 0, 0)
        self.Line3.setObjectName("Line3")
        self.ratioLabel = QtWidgets.QLabel(self.layoutWidget)
        self.ratioLabel.setMinimumSize(QtCore.QSize(45, 0))
        self.ratioLabel.setMaximumSize(QtCore.QSize(45, 20))
        self.ratioLabel.setObjectName("ratioLabel")
        self.Line3.addWidget(self.ratioLabel)
        self.ratioSlider = QtWidgets.QSlider(self.layoutWidget)
        self.ratioSlider.setMinimumSize(QtCore.QSize(192, 0))
        self.ratioSlider.setMaximumSize(QtCore.QSize(180, 20))
        self.ratioSlider.setMaximum(100)
        self.ratioSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ratioSlider.setObjectName("ratioSlider")
        self.Line3.addWidget(self.ratioSlider)
        self.shuffleButton = QtWidgets.QPushButton(Form)
        self.shuffleButton.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.shuffleButton.setObjectName("suffleButton")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 261, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.Line2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.Line2.setContentsMargins(0, 0, 0, 0)
        self.Line2.setObjectName("Line2")
        self.offsetLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.offsetLabel.setMinimumSize(QtCore.QSize(45, 0))
        self.offsetLabel.setMaximumSize(QtCore.QSize(45, 16777215))
        self.offsetLabel.setObjectName("offsetLabel")
        self.Line2.addWidget(self.offsetLabel)
        self.offsetEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.offsetEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.offsetEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.offsetEdit.setObjectName("offsetEdit")
        self.Line2.addWidget(self.offsetEdit)
        self.tangentLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.tangentLabel.setMinimumSize(QtCore.QSize(45, 0))
        self.tangentLabel.setMaximumSize(QtCore.QSize(45, 16777215))
        self.tangentLabel.setObjectName("tangentLabel")
        self.Line2.addWidget(self.tangentLabel)
        self.tangentBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.tangentBox.setMinimumSize(QtCore.QSize(60, 0))
        self.tangentBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.tangentBox.setObjectName("tangentBox")
        self.tangentBox.addItem("")
        self.tangentBox.addItem("")
        self.tangentBox.addItem("")
        self.Line2.addWidget(self.tangentBox)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 260, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.line1 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.line1.setContentsMargins(0, 0, 0, 0)
        self.line1.setObjectName("line1")
        self.numLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.numLabel.setMinimumSize(QtCore.QSize(45, 0))
        self.numLabel.setMaximumSize(QtCore.QSize(45, 16777215))
        self.numLabel.setObjectName("numLabel")
        self.line1.addWidget(self.numLabel)
        self.numEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.numEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.numEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.numEdit.setObjectName("numEdit")
        self.line1.addWidget(self.numEdit)
        self.stackLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.stackLabel.setMinimumSize(QtCore.QSize(45, 0))
        self.stackLabel.setMaximumSize(QtCore.QSize(45, 16777215))
        self.stackLabel.setObjectName("stackLabel")
        self.line1.addWidget(self.stackLabel)
        self.stackEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.stackEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.stackEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.stackEdit.setObjectName("stackEdit")
        self.line1.addWidget(self.stackEdit)

        self.retranslateUi(Form)
        self.linkFunc()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PokerSpring"))
        self.buildButton.setText(_translate("Form", "Build"))
        self.ratioLabel.setText(_translate("Form", "Ratio:"))
        self.shuffleButton.setText(_translate("Form", "Shuffle"))
        self.offsetLabel.setText(_translate("Form", "Offset:"))
        self.tangentLabel.setText(_translate("Form", "Tangent:"))
        self.tangentBox.setItemText(0, _translate("Form", "Linear"))
        self.tangentBox.setItemText(1, _translate("Form", "Sine"))
        self.tangentBox.setItemText(2, _translate("Form", "Cosine"))
        self.numLabel.setText(_translate("Form", "Number:"))
        self.stackLabel.setText(_translate("Form", "Stack:"))

    def linkFunc(self):
        self.numEdit.setText('54')
        self.stackEdit.setText('0.015')
        self.offsetEdit.setText('1.5')

        self.buildButton.clicked.connect(self.build)
        self.shuffleButton.clicked.connect(self.shuffle)
        self.ratioSlider.valueChanged.connect(self.completionLink)
        self.tangentBox.currentIndexChanged.connect(self.tangentLink)

    def shuffle(self):
        pokerSpringFunc.shuffleCards(textureDir = 'C:/Users/Lei/Desktop/cardTexture')

    def build(self):
        num = int(self.numEdit.text())
        stack = float(self.stackEdit.text())
        offset = float(self.offsetEdit.text())
        pokerSpringFunc.deleteNode()
        pokerSpringFunc.buildDeck(num=num, stack=stack, holdValue=offset)

    def completionLink(self):
        sliderV = self.ratioSlider.value()
        cmds.setAttr('pokerPath.completion', sliderV)

    def tangentLink(self):
        tangentV = self.tangentBox.currentIndex()
        pokerSpringFunc.setTangent(tangentV)

class UI(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(406, 139)
        Form.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 368, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Line2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.Line2.setContentsMargins(0, 0, 0, 0)
        self.Line2.setObjectName("Line2")
        self.hvLabel = QtWidgets.QLabel(self.layoutWidget)
        self.hvLabel.setObjectName("hvLabel")
        self.Line2.addWidget(self.hvLabel)
        self.hvEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.hvEdit.setObjectName("hvEdit")
        self.Line2.addWidget(self.hvEdit)
        self.initPosLabel = QtWidgets.QLabel(self.layoutWidget)
        self.initPosLabel.setObjectName("initPosLabel")
        self.Line2.addWidget(self.initPosLabel)
        self.initPosEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.initPosEdit.setObjectName("initPosEdit")
        self.Line2.addWidget(self.initPosEdit)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 100, 181, 24))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.line4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.line4.setContentsMargins(0, 0, 0, 0)
        self.line4.setObjectName("line4")
        self.biasLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.biasLabel.setObjectName("biasLabel")
        self.line4.addWidget(self.biasLabel)
        self.biasSlider = QtWidgets.QSlider(self.layoutWidget_2)
        self.biasSlider.setMinimum(-1)
        self.biasSlider.setMaximum(1)
        self.biasSlider.setPageStep(1)
        self.biasSlider.setOrientation(QtCore.Qt.Horizontal)
        self.biasSlider.setObjectName("biasSlider")
        self.line4.addWidget(self.biasSlider)
        self.buildButton = QtWidgets.QPushButton(Form)
        self.buildButton.setGeometry(QtCore.QRect(310, 100, 75, 23))
        self.buildButton.setObjectName("buildButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 10, 368, 22))
        self.widget.setObjectName("widget")
        self.Line1 = QtWidgets.QHBoxLayout(self.widget)
        self.Line1.setContentsMargins(0, 0, 0, 0)
        self.Line1.setObjectName("Line1")
        self.numLabel = QtWidgets.QLabel(self.widget)
        self.numLabel.setObjectName("numLabel")
        self.Line1.addWidget(self.numLabel)
        self.numEdit = QtWidgets.QLineEdit(self.widget)
        self.numEdit.setObjectName("numEdit")
        self.Line1.addWidget(self.numEdit)
        self.stackLabel = QtWidgets.QLabel(self.widget)
        self.stackLabel.setObjectName("stackLabel")
        self.Line1.addWidget(self.stackLabel)
        self.stackEdit = QtWidgets.QLineEdit(self.widget)
        self.stackEdit.setObjectName("stackEdit")
        self.Line1.addWidget(self.stackEdit)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(20, 70, 361, 24))
        self.widget1.setObjectName("widget1")
        self.Line3 = QtWidgets.QHBoxLayout(self.widget1)
        self.Line3.setContentsMargins(0, 0, 0, 0)
        self.Line3.setObjectName("Line3")
        self.comLabel = QtWidgets.QLabel(self.widget1)
        self.comLabel.setObjectName("comLabel")
        self.Line3.addWidget(self.comLabel)
        self.comSlider = QtWidgets.QSlider(self.widget1)
        self.comSlider.setMaximum(100)
        self.comSlider.setOrientation(QtCore.Qt.Horizontal)
        self.comSlider.setObjectName("comSlider")
        self.Line3.addWidget(self.comSlider)

        self.retranslateUi(Form)
        self.linkFunc()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hvLabel.setText(_translate("Form", "HoldValue"))
        self.initPosLabel.setText(_translate("Form", "InitPos:"))
        self.biasLabel.setText(_translate("Form", "Bias"))
        self.buildButton.setText(_translate("Form", "Build"))
        self.numLabel.setText(_translate("Form", "Number:"))
        self.stackLabel.setText(_translate("Form", "Stack:"))
        self.comLabel.setText(_translate("Form", "Completion"))

    def linkFunc(self):
        self.buildButton.clicked.connect(self.build)
        self.comSlider.valueChanged.connect(self.completionLink)
        self.biasSlider.valueChanged.connect(self.biasLink)

    def build(self):
        pokerSpringFunc.deleteNode()
        pokerSpringFunc.buildDeck()

    def completionLink(self):
        sliderV = self.comSlider.value()
        cmds.setAttr('pokerPath.completion', sliderV)

    def biasLink(self):
        biasV = self.biasSlider.value()
        pokerSpringFunc.setTangent(biasV)

MainWindow = QtWidgets.QMainWindow()
ui = PokerUI()
ui.setupUi(MainWindow)
MainWindow.show()
